### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by gree303** [tricoders/texture-synthesis#2]
I'm trying to "mirror top + left" edges to "right + bottom" edge getting a seamless result as image.
Can you suggest any point to start from. Don't have much experience in java. thx
Example: (action at ~ 0:30)  [Youtube](https://www.youtube.com/watch?v=kQj7FfN2WLA)

**Comment by clayheaton** [comment]
You can either do it manually in Illustrator or programmatically by performing texture synthesis and then generating Wang tiles. This sketch does not generate Wang tiles. However, the procedure for doing so is not complicated. If you Google Wang Tiles and Microsoft Research you'll find a paper that covers the process. Here is a JS implementation of texture synthesis that I did a while ago:

http://clayheaton.github.io/p5jsTiler/index.html

**Comment by gree303** [comment]
Thanks - will look into it.
